### ISSUE TITLE
aiofiles error

### ISSUE THREAD

**Issue by Klaudioz** [thecooltechguy/ComfyUI-ComfyRun#1]
I'm getting the following error:

```
Total VRAM 12287 MB, total RAM 32621 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ComfyRun\__init__.py", line 6, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
```

I tried manually installing it with `pip install aiofiles` and I'm getting the same. I'm using a Windows WM after years of not using windows, so maybe that's the solution and I didn't know how to refresh the environment.

**Comment by thecooltechguy** [comment]
Hmm can you share the Python version you are using?

**Comment by Klaudioz** [comment]
Python 3.10.11

**Comment by thecooltechguy** [comment]
@Klaudioz can you try running `<your python executable> -m pip install aiofiles`?

**Comment by BarrenWardo** [comment]
Hey @Klaudioz 

With the latest merge, this issue should get fixed. Please try reinstalling it from Manager.

#2

**Comment by Klaudioz** [comment]
After uninstalling and re-installing with the Manager, I got the same:

![CleanShot 2023-12-26 at 10 22 45](https://github.com/thecooltechguy/ComfyUI-ComfyRun/assets/632625/09104c5d-fe7a-419c-818c-77395a2234c7)

**Comment by Klaudioz** [comment]
Edit: It worked, I forgot to restart
