### ISSUE TITLE
Comfy Manager UI Issue

### ISSUE THREAD

**Issue by BarrenWardo** [thecooltechguy/ComfyUI-ComfyRun#4]
The ComfyRun messes up the Comfy Manager UI. Screenshots below.

With ComfyRun

<img width="1093" alt="image" src="https://github.com/thecooltechguy/ComfyUI-ComfyRun/assets/86141456/1395e050-adcd-4949-b276-a7ee6022f2d8">

Without ComfyRun [after uninstall]

<img width="1089" alt="image" src="https://github.com/thecooltechguy/ComfyUI-ComfyRun/assets/86141456/51b90e57-4729-4473-bf09-5f76c4659094">

ComfyRun is a good tool but according to me Comfy Manager is a must have and this is messing it up pretty bad. I love the approach of adding the buttons directly on the main view but to fix the Comfy Manager it is okay if you can add a button in the manager or some other way without messing up the UI.

This is not an urgent issue but request you to please fix it.

Thanks!

**Comment by thecooltechguy** [comment]
Hi so sorry about this bug! Just pushed a commit to fix this.

**Comment by Bladed3d** [comment]
Me too!! How do I uninstall this?
